In [1]:
# importing pandas
import pandas as pd

In [8]:
#loading the dataset
csb = pd.read_csv('customer_shopping_behavior_hp_data.csv')

In [9]:
csb.head()

,Customer ID,Age,Gender,Item Purchased,Category,Unit sold,Unit Price,Purchase_Amount_inr,Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,1,2650,2650,Mumbai,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,40,UPI,Fortnightly
1,2,19,Male,Sweater,Clothing,1,3200,3200,Pune,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,42,PhonePe,Fortnightly
2,3,50,Male,Jeans,Clothing,3,3650,10950,Delhi,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,46,Google Pay,Weekly
3,4,21,Male,Sandals,Footwear,3,4500,13500,Bengaluru,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,42,Paytm,Weekly
4,5,45,Male,Blouse,Clothing,3,2450,7350,Hyderabad,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,50,Credit Card,Annually

In [30]:
csb.shape

(4500, 21)

In [10]:
csb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4500 entries, 0 to 4499
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             4500 non-null   int64
 1   Age                     4500 non-null   int64
 2   Gender                  4500 non-null   object
 3   Item Purchased          4500 non-null   object
 4   Category                4500 non-null   object
 5   Unit sold               4500 non-null   int64
 6   Unit Price              4500 non-null   int64
 7   Purchase_Amount_inr     4500 non-null   int64
 8   Location                4500 non-null   object
 9   Size                    4500 non-null   object
 10  Color                   4500 non-null   object
 11  Season                  4500 non-null   object
 12  Review Rating           4446 non-null   float64
 13  Subscription Status     4500 non-null   object
 14  Shipping Type           4500 non-null   object
 15  Discount Applied        4500 non-null   object
 16  Promo Code Used         4500 non-null   object
 17  Previous Purchases      4500 non-null   int64
 18  Payment Method          4500 non-null   object
 19  Frequency of Purchases  4500 non-null   object
dtypes: float64(1), int64(6), object(13)
memory usage: 703.3+ KB

In [11]:
#dataset statistics
csb.describe(include= 'all')

,Customer ID,Age,Gender,Item Purchased,Category,Unit sold,Unit Price,Purchase_Amount_inr,Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,4500.000000,4500.000000,4500,4500,4500,4500.000000,4500.000000,4500.000000,4500,4500,4500,4500,4446.000000,4500,4500,4500,4500,4500.000000,4500,4500
unique,NaN,NaN,2,25,4,NaN,NaN,NaN,60,4,25,4,NaN,2,6,2,2,NaN,12,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,NaN,NaN,Navi Mumbai,M,Olive,Spring,NaN,No,Free Shipping,Yes,Yes,NaN,Credit Card,Annually
freq,NaN,NaN,2920,207,2024,NaN,NaN,NaN,79,2032,214,1140,NaN,2847,782,2277,2277,NaN,639,679
mean,2250.500000,44.340000,NaN,NaN,NaN,2.039556,2991.500000,6080.611111,NaN,NaN,NaN,NaN,3.754116,NaN,NaN,NaN,NaN,25.628889,NaN,NaN
std,1299.182435,15.410958,NaN,NaN,NaN,0.886910,1182.413772,3673.234677,NaN,NaN,NaN,NaN,0.716666,NaN,NaN,NaN,NaN,14.540791,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,1.000000,1000.000000,1000.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,1125.750000,31.000000,NaN,NaN,NaN,1.000000,1950.000000,3300.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,2250.500000,44.000000,NaN,NaN,NaN,2.000000,3000.000000,4950.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,26.000000,NaN,NaN
75%,3375.250000,57.000000,NaN,NaN,NaN,3.000000,4012.500000,8500.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,4500.000000,75.000000,NaN,NaN,NaN,9.000000,5000.000000,27900.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [12]:
csb.isnull().sum() #returns sum of null values for each column

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Unit sold                  0
Unit Price                 0
Purchase_Amount_inr        0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             54
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

### 54 null values in 'review rating'

In [13]:
csb['Review Rating'] = csb.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [14]:
csb.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Unit sold                 0
Unit Price                0
Purchase_Amount_inr       0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

#### here we have imputed all the null values in 'Review rating' column

In [16]:
csb.duplicated().any()

False

In [17]:
csb.duplicated().sum()

0

In [32]:
csb.nunique()

customer_id                4500
age                          58
gender                        2
item_purchased               25
category                      4
unit_sold                     9
unit_price                   81
purchase_amount_inr         207
location                     60
size                          4
color                        25
season                        4
review_rating                26
subscription_status           2
shipping_type                 6
discount_applied              2
previous_purchases           50
payment_method               12
frequency_of_purchases        7
age_group                     4
purchase_frequency_days       5
dtype: int64

In [34]:
# replacing current column names with snkae casing(lowercase+underscore) column names
csb.columns = csb.columns.str.lower() #to make it lowercase
csb.columns = csb.columns.str.replace(' ','_') #replacing space with underscore

In [35]:
csb.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'unit_sold', 'unit_price', 'purchase_amount_inr', 'location', 'size',
       'color', 'season', 'review_rating', 'subscription_status',
       'shipping_type', 'discount_applied', 'previous_purchases',
       'payment_method', 'frequency_of_purchases', 'age_group',
       'purchase_frequency_days'],
      dtype='object')

In [36]:
#create a column age_group
labels = ['Young Adult', 'Adult', 'Middle Age', 'Senior']
csb['age_group'] = pd.qcut(csb['age'],q=4, labels = labels)

In [37]:
csb[['age','age_group']].head(10)

   age    age_group
0   55   Middle Age
1   19  Young Adult
2   50   Middle Age
3   21  Young Adult
4   45   Middle Age
5   46   Middle Age
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57   Middle Age

In [38]:
# create column purchase_frequency_days

frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

csb['purchase_frequency_days'] = csb['frequency_of_purchases'].map(frequency_mapping) #using map() to replace the text with the matching number in the column

In [39]:
csb[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [40]:
csb[['discount_applied','promo_code_used']].head(10)

KeyError: "['promo_code_used'] not in index"

these two column seems to have same data

In [41]:
(csb['discount_applied'] == csb['promo_code_used']).all()

KeyError: 'promo_code_used'

#### The validation confirmed that whenever a discount was applied, the promo code status matched exactly. 
#### Since both columns store the same information, retaining only one avoids redundancy and simplifies the dataset.

In [28]:
csb = csb.drop('promo_code_used', axis = 1)

# axis=0 (default) → Work down the rows (column-wise) //Go up and down (↓)
# axis=1 → Work across the columns (row-wise) //Go left to right (→)

In [29]:
csb.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'unit_sold', 'unit_price', 'purchase_amount_inr', 'location', 'size',
       'color', 'season', 'review_rating', 'subscription_status',
       'shipping_type', 'discount_applied', 'previous_purchases',
       'payment_method', 'frequency_of_purchases', 'age_group',
       'purchase_frequency_days'],
      dtype='object')

# connecting database to PostgreSQL

In [22]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\hp\anaconda3\lib\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in c:\users\hp\anaconda3\lib\site-packages (2.0.34)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\hp\anaconda3\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\hp\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)
Note: you may need to restart the kernel to use updated packages.

In [42]:
from sqlalchemy import create_engine

In [43]:
#step 1: connect to postgreSQL
username = "postgres" #default user
password = "root" #the pass you set during installation
host = "localhost"
post = "5432"
database = "customer_behavior_analysis" #the database you created in pgAdmin

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{post}/{database}")

#step 2: Load Dataframe into postgreSQL
table_name = "customer_data" #choose any table name
csb.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"data successfully loaded into table'{table_name}' in database '{database}'.")

data successfully loaded into table'customer_data' in database 'customer_behavior_analysis'.